name: Build and deploy Python app to Azure Web App - RestApiPython

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python version
      uses: actions/setup-python@v2
      with:
        python-version: '3.12' # Use the specific version supported by Azure

    - name: Install dependencies
      run: |
        python -m venv venv
        . venv/bin/activate
        pip install -r requirements.txt

    # If you have tests, you can run them here
    # - name: Run tests
    #   run: |
    #     . venv/bin/activate
    #     pytest

    - name: Zip the application
      run: zip -r release.zip . -x venv/\* \*.git\* \*__pycache__\* \*.pytest_cache\* \*.github\*

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'RestApiPython'
        slot-name: 'Production'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9071909112174634B784F8200916AB53 }}
        package: release.zip
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
